version: "3.5"

services:
  api:
    image: api-bacc:latest
    container_name: api_bacc
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        STRAPI_VERSION: ${STRAPI_VERSION}
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URI: ${DATABASE_URI}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    depends_on:
      - db
    networks:
      - api-bacc-network
    ports:
      - "${WEB_PORT:-80}:1337"
    #volumes:
    # - ./app/config/middleware.js:/app/config/middleware.js
    # command: 'strapi start'

  db:
    image: mongo:4
    container_name: api_mongo
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - api-bacc-network
    volumes:
      - apidatadb:/data/db
    ports:
      - "27017:27017"

networks:
  api-bacc-network:
    driver: bridge

volumes:
  apidatadb:
