version: "3.5"

services:
  api-convert:
    image: node:12
    container_name: api_convert
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URI: ${DATABASE_URI}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      DATA_SETS: "${DATA_SETS}"
    volumes:
      - ./data:/data
    command: '/bin/bash -xc "( cd /data; npm ci; npm run convert )"'
